spring:
#  thymeleaf:
#    cache: false
#    prefix: classpath:/templates/
#    suffix: .html
#    encoding: UTF-8
#    mode: HTML5
  datasource:
        name: test
        url: jdbc:mysql://localhost/library?useSSL=false&characterEncoding=utf8&serverTimezone=GMT%2B8&allowMultiQueries=true
        username: root
        password: 1126
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver

        druid:
          filters: stat,wall
          aop-patterns: cn.lightina.*
          stat-view-servlet:
            enabled: true
            login-username: admin
            login-password: admin
            reset-enable: false
          filter:
            wall:
              config:
                multi-statement-allow: true
              enabled: true
            stat:
              db-type: mysql


  mail:
    host: smtp.163.com
    username: managebooks@163.com
    password: 654321bm
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true

mybatis:
  mapper-locations: classpath:Mapper/*.xml
#  type-aliases-package: cn.lightina.managebooks.pojo
  configuration:
    map-underscore-to-camel-case: true

mail:
  fromMail:
    addr: managebooks@163.com